name: Test & Lint

on:
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.2"

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint
